/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../../eurydice/eurydice --config ../../kyber-c.yaml ../libcrux_kyber.llbc
  F* version: b5cb71b8
  KaRaMeL version: 1282f04f
 */

#include "internal/core.h"

typedef size_t RangeTo__size_t;

typedef size_t RangeFrom__size_t;

typedef struct Option__size_t_s
{
  core_option_Option__size_t_tags tag;
  size_t f0;
}
Option__size_t;

typedef struct Option__uint32_t_s
{
  core_option_Option__size_t_tags tag;
  uint32_t f0;
}
Option__uint32_t;

typedef struct Option__int32_t_s
{
  core_option_Option__size_t_tags tag;
  int32_t f0;
}
Option__int32_t;

