/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/jonathan/Code/eurydice/eurydice --config ../../kyber-c.yaml ../libcrux_kyber.llbc
  F* version: 13bd96aa
  KaRaMeL version: 9926c187
 */

#include "internal/core.h"

typedef size_t RangeFrom__size_t;

typedef size_t RangeTo__size_t;

