/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/franziskus/repos/eurydice//eurydice --config ../../kyber-c.yaml ../libcrux_kyber.llbc
  F* version: a32b316e
  KaRaMeL version: a1e1b1f2
 */

#include "internal/core.h"

typedef size_t RangeFrom__size_t;

typedef size_t RangeTo__size_t;

