/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/franziskus/repos/eurydice//eurydice ../libcrux_kyber.llbc
  F* version: d0aa54cf
  KaRaMeL version: b329675d
 */

#include "Eurydice.h"



