/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/franziskus/repos/eurydice//eurydice ../libcrux_kyber.llbc
  F* version: d0aa54cf
  KaRaMeL version: 8e0595bd
 */

#include "LowStar_Ignore.h"



