/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/franziskus/repos/eurydice//eurydice --config ../c.yaml ../../libcrux_sha3.llbc
  F* version: a32b316e
  KaRaMeL version: 020de30f
 */

#ifndef __internal_core_H
#define __internal_core_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "../core.h"
#include "eurydice_glue.h"

#define core_option_None 0
#define core_option_Some 1

typedef uint8_t core_option_Option__size_t_tags;

typedef struct core_option_Option__size_t_s
{
  core_option_Option__size_t_tags tag;
  size_t f0;
}
core_option_Option__size_t;

#define core_result_Ok 0
#define core_result_Err 1

typedef uint8_t core_result_Result_____core_fmt_Error_tags;

static inline uint64_t core_num__u64_9__from_le_bytes(uint8_t x0[8U]);

static inline void core_num__u64_9__to_le_bytes(uint64_t x0, uint8_t x1[8U]);

#define core_array___core__clone__Clone_for__Array_T__N___20__clone(len, src, dst, elem_type, _ret_t) \
  (memcpy(dst, src, len * sizeof(elem_type)))

#if defined(__cplusplus)
}
#endif

#define __internal_core_H_DEFINED
#endif
