/*
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/franziskus/repos/eurydice//eurydice --config
  ../c.yaml ../../libcrux_sha3.llbc F* version: a32b316e KaRaMeL version:
  020de30f
 */

#ifndef __internal_libcrux_sha3_H
#define __internal_libcrux_sha3_H

#if defined(__cplusplus)
extern "C"
{
#endif

#include "../libcrux_sha3.h"
#include "eurydice_glue.h"
#include "internal/core.h"

  typedef struct K___Eurydice_slice_uint8_t_Eurydice_slice_uint8_t_s
  {
    Eurydice_slice fst;
    Eurydice_slice snd;
  } K___Eurydice_slice_uint8_t_Eurydice_slice_uint8_t;

#if defined(__cplusplus)
}
#endif

#define __internal_libcrux_sha3_H_DEFINED
#endif
