/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/franziskus/repos/eurydice//eurydice --config ../c.yaml ../../libcrux_ml_kem.llbc
  F* version: a32b316e
  KaRaMeL version: 3568f417
 */

#ifndef __internal_libcrux_ml_kem_H
#define __internal_libcrux_ml_kem_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "internal/core.h"
#include "../libcrux_ml_kem.h"
#include "eurydice_glue.h"

typedef struct core_option_Option__Eurydice_slice_uint8_t_s
{
  core_option_Option__size_t_tags tag;
  Eurydice_slice f0;
}
core_option_Option__Eurydice_slice_uint8_t;

#if defined(__cplusplus)
}
#endif

#define __internal_libcrux_ml_kem_H_DEFINED
#endif
