/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/bhargava/Desktop/repositories/eurydice/eurydice --config ../../kyber-c.yaml ../libcrux_kyber.llbc
  F* version: a32b316e
  KaRaMeL version: 08bfa78a
 */

#ifndef __internal_libcrux_kyber_H
#define __internal_libcrux_kyber_H

#include "internal/core.h"
#include "../libcrux_kyber.h"
#include "eurydice_glue.h"

typedef struct core_ops_range_Range__uint32_t_s
{
  uint32_t start;
  uint32_t end;
}
core_ops_range_Range__uint32_t;

typedef struct core_ops_range_Range__int32_t_s
{
  int32_t start;
  int32_t end;
}
core_ops_range_Range__int32_t;

typedef struct core_option_Option__Eurydice_slice_uint8_t_s
{
  core_option_Option__size_t_tags tag;
  Eurydice_slice f0;
}
core_option_Option__Eurydice_slice_uint8_t;

typedef struct K___Eurydice_slice_uint8_t_Eurydice_slice_uint8_t_s
{
  Eurydice_slice fst;
  Eurydice_slice snd;
}
K___Eurydice_slice_uint8_t_Eurydice_slice_uint8_t;


#define __internal_libcrux_kyber_H_DEFINED
#endif
