set(ALGORITHMS blake2)
set(ALGORITHM_HACL_FILES HACL_FILES_blake2)
set(HACL_FILES_blake2 ${PROJECT_SOURCE_DIR}/src/Hacl_Hash_Blake2.c ${PROJECT_SOURCE_DIR}/src/Hacl_Kremlib.c ${PROJECT_SOURCE_DIR}/src/Lib_Memzero0.c ${PROJECT_SOURCE_DIR}/src/Hacl_Hash_Blake2b_256.c ${PROJECT_SOURCE_DIR}/src/Hacl_Kremlib.c ${PROJECT_SOURCE_DIR}/src/Lib_Memzero0.c ${PROJECT_SOURCE_DIR}/src/Hacl_Hash_Blake2.c ${PROJECT_SOURCE_DIR}/src/Hacl_Streaming_Blake2b_256.c ${PROJECT_SOURCE_DIR}/src/Hacl_Streaming_Blake2.c ${PROJECT_SOURCE_DIR}/src/Hacl_Kremlib.c ${PROJECT_SOURCE_DIR}/src/Hacl_Spec.c ${PROJECT_SOURCE_DIR}/src/Hacl_Hash_Blake2.c ${PROJECT_SOURCE_DIR}/src/Lib_Memzero0.c ${PROJECT_SOURCE_DIR}/src/Hacl_Hash_Blake2b_256.c ${PROJECT_SOURCE_DIR}/src/Hacl_Hash_Blake2s_128.c ${PROJECT_SOURCE_DIR}/src/Hacl_Kremlib.c ${PROJECT_SOURCE_DIR}/src/Lib_Memzero0.c ${PROJECT_SOURCE_DIR}/src/Hacl_Hash_Blake2.c)
set(ALGORITHM_EVERCRYPT_FILES )
set(REQUIRED_FEATURES_Hacl_Hash_Blake2b_256 avx2)
set(REQUIRED_FEATURES_Hacl_Streaming_Blake2b_256 avx2)
set(REQUIRED_FEATURES_Hacl_Hash_Blake2s_128 avx)
set(REQUIRED_FEATURES_Hacl_Chacha20Poly1305_128 avx)
set(REQUIRED_FEATURES_Hacl_Chacha20Poly1305_256 avx2)
set(REQUIRED_FEATURES_Hacl_Chacha20_Vec256 avx2)
set(REQUIRED_FEATURES_Hacl_Poly1305_256 avx2)
set(CPU_FEATURE_avx2 ${PROJECT_SOURCE_DIR}/src/Hacl_Hash_Blake2b_256.c ${PROJECT_SOURCE_DIR}/src/Hacl_Streaming_Blake2b_256.c ${PROJECT_SOURCE_DIR}/src/Hacl_Chacha20Poly1305_256.c ${PROJECT_SOURCE_DIR}/src/Hacl_Chacha20_Vec256.c ${PROJECT_SOURCE_DIR}/src/Hacl_Poly1305_256.c)
set(CPU_FEATURE_avx ${PROJECT_SOURCE_DIR}/src/Hacl_Hash_Blake2s_128.c ${PROJECT_SOURCE_DIR}/src/Hacl_Chacha20Poly1305_128.c)
set(ALGORITHM_TEST_FILES TEST_FILES_blake2b TEST_FILES_p256)
set(TEST_FILES_blake2b blake2b.c)
set(TEST_FILES_p256 p256.c)
