set(SOURCES_std ${PROJECT_SOURCE_DIR}/src/Hacl_Hash_Blake2.c ${PROJECT_SOURCE_DIR}/src/Hacl_Kremlib.c ${PROJECT_SOURCE_DIR}/src/Lib_Memzero0.c)
set(SOURCES_vec256 ${PROJECT_SOURCE_DIR}/src/Hacl_Hash_Blake2b_256.c ${PROJECT_SOURCE_DIR}/src/Hacl_Streaming_Blake2b_256.c ${PROJECT_SOURCE_DIR}/src/Hacl_Streaming_Blake2.c ${PROJECT_SOURCE_DIR}/src/Hacl_Spec.c)
set(SOURCES_vec128 ${PROJECT_SOURCE_DIR}/src/Hacl_Hash_Blake2s_128.c ${PROJECT_SOURCE_DIR}/src/Hacl_Streaming_Blake2s_128.c ${PROJECT_SOURCE_DIR}/src/Hacl_Streaming_Blake2.c ${PROJECT_SOURCE_DIR}/src/Hacl_Spec.c)
set(ALGORITHMS blake2)
set(INCLUDE_PATHS ${PROJECT_SOURCE_DIR}/include ${PROJECT_SOURCE_DIR}/kremlin/include/ ${PROJECT_SOURCE_DIR}/kremlin/kremlib/dist/minimal)
set(TEST_SOURCES ${PROJECT_SOURCE_DIR}/tests/blake2b.cc ${PROJECT_SOURCE_DIR}/tests/blake2s.cc)
set(ALGORITHM_TEST_FILES TEST_FILES_blake2)
set(TEST_FILES_blake2 blake2b.cc blake2s.cc)
