set(SOURCES_std ${PROJECT_SOURCE_DIR}/src/Hacl_Hash_Blake2.c ${PROJECT_SOURCE_DIR}/src/Hacl_Kremlib.c ${PROJECT_SOURCE_DIR}/src/Lib_Memzero0.c ${PROJECT_SOURCE_DIR}/src/Hacl_Chacha20Poly1305_32.c ${PROJECT_SOURCE_DIR}/src/Hacl_Chacha20.c ${PROJECT_SOURCE_DIR}/src/Hacl_Poly1305_32.c)
set(SOURCES_vec256 ${PROJECT_SOURCE_DIR}/src/Hacl_Hash_Blake2b_256.c ${PROJECT_SOURCE_DIR}/src/Hacl_Streaming_Blake2b_256.c ${PROJECT_SOURCE_DIR}/src/Hacl_Streaming_Blake2.c ${PROJECT_SOURCE_DIR}/src/Hacl_Spec.c ${PROJECT_SOURCE_DIR}/src/Hacl_Chacha20Poly1305_256.c ${PROJECT_SOURCE_DIR}/src/Hacl_Chacha20_Vec256.c ${PROJECT_SOURCE_DIR}/src/Hacl_Poly1305_256.c)
set(SOURCES_vec128 ${PROJECT_SOURCE_DIR}/src/Hacl_Hash_Blake2s_128.c ${PROJECT_SOURCE_DIR}/src/Hacl_Streaming_Blake2s_128.c ${PROJECT_SOURCE_DIR}/src/Hacl_Streaming_Blake2.c ${PROJECT_SOURCE_DIR}/src/Hacl_Spec.c ${PROJECT_SOURCE_DIR}/src/Hacl_Chacha20Poly1305_128.c ${PROJECT_SOURCE_DIR}/src/Hacl_Chacha20_Vec128.c ${PROJECT_SOURCE_DIR}/src/Hacl_Poly1305_128.c)
set(ALGORITHMS blake2 chacha20poly1305)
set(INCLUDE_PATHS ${PROJECT_SOURCE_DIR}/include ${PROJECT_SOURCE_DIR}/kremlin/include/ ${PROJECT_SOURCE_DIR}/kremlin/kremlib/dist/minimal)
set(TEST_SOURCES ${PROJECT_SOURCE_DIR}/tests/blake2b.cc ${PROJECT_SOURCE_DIR}/tests/blake2s.cc ${PROJECT_SOURCE_DIR}/tests/chacha20poly1305.cc)
set(ALGORITHM_TEST_FILES TEST_FILES_blake2 TEST_FILES_chacha20poly1305)
set(TEST_FILES_blake2 blake2b.cc blake2s.cc)
set(TEST_FILES_chacha20poly1305 chacha20poly1305.cc)
