
# Set configuration constants
set(HACL_ARCHITECTURE_UNKNOWN 0)
set(HACL_ARCHITECTURE_X86 1)
set(HACL_ARCHITECTURE_X64 2)
set(HACL_ARCHITECTURE_ARM32 3)
set(HACL_ARCHITECTURE_ARM64 4)
set(HACL_ARCHITECTURE_SYSTEMZ 5)
set(HACL_ARCHITECTURE_POWERPC64 6)
