
# Set configuration constants
set(EVERCRYPT_ARCHITECTURE_UNKNOWN 0)
set(EVERCRYPT_ARCHITECTURE_X86 1)
set(EVERCRYPT_ARCHITECTURE_X64 2)
set(EVERCRYPT_ARCHITECTURE_ARM32 3)
set(EVERCRYPT_ARCHITECTURE_ARM64 4)
set(EVERCRYPT_ARCHITECTURE_SYSTEMZ 5)
set(EVERCRYPT_ARCHITECTURE_POWERPC64 6)
