#define HACL_VERSION_MAJOR 0
#define HACL_VERSION_MINOR 1
#define HACL_VERSION_PATCH 0
#define HACL_VERSION_TWEAK alpha.1

#define TARGET_ARCHITECTURE_ID_UNKNOWN 0
#define TARGET_ARCHITECTURE_ID_X86 1
#define TARGET_ARCHITECTURE_ID_X64 2
#define TARGET_ARCHITECTURE_ID_ARM32 3
#define TARGET_ARCHITECTURE_ID_ARM64 4
#define TARGET_ARCHITECTURE_ID_SYSTEMZ 5
#define TARGET_ARCHITECTURE_ID_POWERPC64 6

#define TARGET_ARCHITECTURE 4

#define HACL_CAN_COMPILE_VEC128 1
#define HACL_CAN_COMPILE_UINT128 1
#define LINUX_NO_EXPLICIT_BZERO 1

#ifndef HACL_CAN_COMPILE_VEC128
    #define Lib_IntVector_Intrinsics_vec128 void *
#endif
#ifndef HACL_CAN_COMPILE_VEC256
    #define Lib_IntVector_Intrinsics_vec256 void *
#endif
