/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/franziskus/repos/eurydice//eurydice --config ../../kyber-c.yaml ../libcrux_kyber.llbc
  F* version: a32b316e
  KaRaMeL version: abb38e1d
 */

#ifndef __core_H
#define __core_H

#include "eurydice_glue.h"

#define core_option_None 0
#define core_option_Some 1

typedef uint8_t core_option_Option__size_t_tags;

typedef struct core_ops_range_Range__size_t_s
{
  size_t start;
  size_t end;
}
core_ops_range_Range__size_t;


#define __core_H_DEFINED
#endif
