/*
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/franziskus/repos/eurydice//eurydice
  ../libcrux_kyber.llbc F* version: d0aa54cf KaRaMeL version: 0eda808b
 */

#ifndef __libcrux_kyber_H
#define __libcrux_kyber_H

#include "Eurydice.h"
#include "eurydice_glue.h"

#define LIBCRUX_KYBER_CONSTANTS_FIELD_MODULUS ((int32_t)3329)

#define LIBCRUX_KYBER_CONSTANTS_BITS_PER_COEFFICIENT ((size_t)12U)

#define LIBCRUX_KYBER_CONSTANTS_COEFFICIENTS_IN_RING_ELEMENT ((size_t)256U)

#define LIBCRUX_KYBER_CONSTANTS_BITS_PER_RING_ELEMENT                          \
  (LIBCRUX_KYBER_CONSTANTS_COEFFICIENTS_IN_RING_ELEMENT * (size_t)12U)

#define LIBCRUX_KYBER_CONSTANTS_BYTES_PER_RING_ELEMENT                         \
  (LIBCRUX_KYBER_CONSTANTS_BITS_PER_RING_ELEMENT / (size_t)8U)

#define LIBCRUX_KYBER_CONSTANTS_REJECTION_SAMPLING_SEED_SIZE                   \
  ((size_t)168U * (size_t)5U)

#define LIBCRUX_KYBER_CONSTANTS_SHARED_SECRET_SIZE ((size_t)32U)

#define LIBCRUX_KYBER_CONSTANTS_CPA_PKE_KEY_GENERATION_SEED_SIZE ((size_t)32U)

#define LIBCRUX_KYBER_CONSTANTS_H_DIGEST_SIZE ((size_t)32U)

#define LIBCRUX_KYBER_ARITHMETIC_MONTGOMERY_SHIFT (16U)

#define LIBCRUX_KYBER_ARITHMETIC_MONTGOMERY_R                                  \
  ((int32_t)1 << (uint32_t)LIBCRUX_KYBER_ARITHMETIC_MONTGOMERY_SHIFT)

uint32_t
libcrux_kyber_arithmetic_get_n_least_significant_bits(uint8_t n,
                                                      uint32_t value);

#define LIBCRUX_KYBER_ARITHMETIC_BARRETT_SHIFT ((int64_t)26)

#define LIBCRUX_KYBER_ARITHMETIC_BARRETT_R                                     \
  ((int64_t)1 << (uint32_t)LIBCRUX_KYBER_ARITHMETIC_BARRETT_SHIFT)

#define LIBCRUX_KYBER_ARITHMETIC_BARRETT_MULTIPLIER ((int64_t)20159)

int32_t
libcrux_kyber_arithmetic_barrett_reduce(int32_t value);

#define LIBCRUX_KYBER_ARITHMETIC_INVERSE_OF_MODULUS_MOD_R (62209U)

int32_t
libcrux_kyber_arithmetic_montgomery_reduce(int32_t value);

int32_t
libcrux_kyber_arithmetic_montgomery_multiply_sfe_by_fer(int32_t fe,
                                                        int32_t fer);

#define LIBCRUX_KYBER_ARITHMETIC_MONTGOMERY_R_SQUARED_MOD_FIELD_MODULUS        \
  ((int32_t)1353)

int32_t
libcrux_kyber_arithmetic_to_standard_domain(int32_t mfe);

uint16_t
libcrux_kyber_arithmetic_to_unsigned_representative(int32_t fe);

typedef int32_t libcrux_kyber_arithmetic_PolynomialRingElement[256U];

void
  libcrux_kyber_arithmetic__libcrux_kyber__arithmetic__PolynomialRingElement_1__clone(
    int32_t (*self)[256U],
    int32_t ret[256U]);

extern const int32_t
  libcrux_kyber_arithmetic__libcrux_kyber__arithmetic__PolynomialRingElement__ZERO
    [256U];

uint8_t
libcrux_kyber_compress_compress_message_coefficient(uint16_t fe);

int32_t
libcrux_kyber_compress_compress_ciphertext_coefficient(uint8_t coefficient_bits,
                                                       uint16_t fe);

int32_t
libcrux_kyber_compress_decompress_message_coefficient(int32_t fe);

int32_t
libcrux_kyber_compress_decompress_ciphertext_coefficient(
  uint8_t coefficient_bits,
  int32_t fe);

uint8_t
libcrux_kyber_constant_time_ops_is_non_zero(uint8_t value);

void
libcrux_kyber_constant_time_ops_select_shared_secret_in_constant_time(
  Eurydice_slice lhs,
  Eurydice_slice rhs,
  uint8_t selector,
  uint8_t ret[32U]);

extern void
libcrux_digest_sha3_512(Eurydice_slice x0, uint8_t x1[64U]);

void
libcrux_kyber_hash_functions_G(Eurydice_slice input, uint8_t ret[64U]);

extern void
libcrux_digest_sha3_256(Eurydice_slice x0, uint8_t x1[32U]);

void
libcrux_kyber_hash_functions_H(Eurydice_slice input, uint8_t ret[32U]);

extern bool
libcrux_platform_simd256_support(void);

typedef struct K___uint8_t_uint8_t_uint8_t_s
{
  uint8_t fst;
  uint8_t snd;
  uint8_t thd;
} K___uint8_t_uint8_t_uint8_t;

K___uint8_t_uint8_t_uint8_t
libcrux_kyber_serialize_compress_coefficients_3(uint16_t coefficient1,
                                                uint16_t coefficient2);

void
libcrux_kyber_serialize_serialize_uncompressed_ring_element(int32_t re[256U],
                                                            uint8_t ret[384U]);

void
libcrux_kyber_serialize_deserialize_to_uncompressed_ring_element(
  Eurydice_slice serialized,
  int32_t ret[256U]);

void
libcrux_kyber_sampling_sample_from_binomial_distribution_2(
  Eurydice_slice randomness,
  int32_t ret[256U]);

void
libcrux_kyber_sampling_sample_from_binomial_distribution_3(
  Eurydice_slice randomness,
  int32_t ret[256U]);

extern const int32_t libcrux_kyber_ntt_ZETAS_TIMES_MONTGOMERY_R[128U];

void
libcrux_kyber_ntt_ntt_at_layer(size_t* zeta_i,
                               int32_t re[256U],
                               size_t layer,
                               size_t initial_coefficient_bound,
                               int32_t ret[256U]);

void
libcrux_kyber_ntt_ntt_at_layer_3(size_t* zeta_i,
                                 int32_t re[256U],
                                 size_t layer,
                                 int32_t ret[256U]);

void
libcrux_kyber_ntt_ntt_binomially_sampled_ring_element(int32_t re[256U],
                                                      int32_t ret[256U]);

void
libcrux_kyber_sampling_rejection_sampling_panic_with_diagnostic(void);

void
libcrux_kyber_sampling_sample_from_uniform_distribution(
  uint8_t randomness[840U],
  int32_t ret[256U]);

typedef struct K___int32_t_int32_t_s
{
  int32_t fst;
  int32_t snd;
} K___int32_t_int32_t;

K___int32_t_int32_t
libcrux_kyber_ntt_ntt_multiply_binomials(K___int32_t_int32_t _,
                                         K___int32_t_int32_t _0,
                                         int32_t zeta);

void libcrux_kyber_ntt_ntt_multiply(int32_t (*lhs)[256U],
                                    int32_t (*rhs)[256U],
                                    int32_t ret[256U]);

typedef struct K___uint8_t_uint8_t_uint8_t_uint8_t_uint8_t_s
{
  uint8_t fst;
  uint8_t snd;
  uint8_t thd;
  uint8_t f3;
  uint8_t f4;
} K___uint8_t_uint8_t_uint8_t_uint8_t_uint8_t;

K___uint8_t_uint8_t_uint8_t_uint8_t_uint8_t
libcrux_kyber_serialize_compress_coefficients_10(int32_t coefficient1,
                                                 int32_t coefficient2,
                                                 int32_t coefficient3,
                                                 int32_t coefficient4);

typedef struct
  K___uint8_t_uint8_t_uint8_t_uint8_t_uint8_t_uint8_t_uint8_t_uint8_t_uint8_t_uint8_t_uint8_t_s
{
  uint8_t fst;
  uint8_t snd;
  uint8_t thd;
  uint8_t f3;
  uint8_t f4;
  uint8_t f5;
  uint8_t f6;
  uint8_t f7;
  uint8_t f8;
  uint8_t f9;
  uint8_t f10;
} K___uint8_t_uint8_t_uint8_t_uint8_t_uint8_t_uint8_t_uint8_t_uint8_t_uint8_t_uint8_t_uint8_t;

K___uint8_t_uint8_t_uint8_t_uint8_t_uint8_t_uint8_t_uint8_t_uint8_t_uint8_t_uint8_t_uint8_t
libcrux_kyber_serialize_compress_coefficients_11(int32_t coefficient1,
                                                 int32_t coefficient2,
                                                 int32_t coefficient3,
                                                 int32_t coefficient4,
                                                 int32_t coefficient5,
                                                 int32_t coefficient6,
                                                 int32_t coefficient7,
                                                 int32_t coefficient8);

void
libcrux_kyber_ntt_invert_ntt_at_layer(size_t* zeta_i,
                                      int32_t re[256U],
                                      size_t layer,
                                      int32_t ret[256U]);

void
libcrux_kyber_serialize_deserialize_then_decompress_message(
  uint8_t serialized[32U],
  int32_t ret[256U]);

K___uint8_t_uint8_t_uint8_t_uint8_t_uint8_t
libcrux_kyber_serialize_compress_coefficients_5(uint8_t coefficient2,
                                                uint8_t coefficient1,
                                                uint8_t coefficient4,
                                                uint8_t coefficient3,
                                                uint8_t coefficient5,
                                                uint8_t coefficient7,
                                                uint8_t coefficient6,
                                                uint8_t coefficient8);

typedef struct K___int32_t_int32_t_int32_t_int32_t_s
{
  int32_t fst;
  int32_t snd;
  int32_t thd;
  int32_t f3;
} K___int32_t_int32_t_int32_t_int32_t;

K___int32_t_int32_t_int32_t_int32_t
libcrux_kyber_serialize_decompress_coefficients_10(int32_t byte2,
                                                   int32_t byte1,
                                                   int32_t byte3,
                                                   int32_t byte4,
                                                   int32_t byte5);

void
libcrux_kyber_serialize_deserialize_then_decompress_10(
  Eurydice_slice serialized,
  int32_t ret[256U]);

typedef struct
  K___int32_t_int32_t_int32_t_int32_t_int32_t_int32_t_int32_t_int32_t_s
{
  int32_t fst;
  int32_t snd;
  int32_t thd;
  int32_t f3;
  int32_t f4;
  int32_t f5;
  int32_t f6;
  int32_t f7;
} K___int32_t_int32_t_int32_t_int32_t_int32_t_int32_t_int32_t_int32_t;

K___int32_t_int32_t_int32_t_int32_t_int32_t_int32_t_int32_t_int32_t
libcrux_kyber_serialize_decompress_coefficients_11(int32_t byte2,
                                                   int32_t byte1,
                                                   int32_t byte3,
                                                   int32_t byte5,
                                                   int32_t byte4,
                                                   int32_t byte6,
                                                   int32_t byte7,
                                                   int32_t byte9,
                                                   int32_t byte8,
                                                   int32_t byte10,
                                                   int32_t byte11);

void
libcrux_kyber_serialize_deserialize_then_decompress_11(
  Eurydice_slice serialized,
  int32_t ret[256U]);

void
libcrux_kyber_ntt_ntt_at_layer_3328(size_t* zeta_i,
                                    int32_t re[256U],
                                    size_t layer,
                                    int32_t ret[256U]);

K___int32_t_int32_t
libcrux_kyber_serialize_decompress_coefficients_4(uint8_t* byte);

void
libcrux_kyber_serialize_deserialize_then_decompress_4(Eurydice_slice serialized,
                                                      int32_t ret[256U]);

K___int32_t_int32_t_int32_t_int32_t_int32_t_int32_t_int32_t_int32_t
libcrux_kyber_serialize_decompress_coefficients_5(int32_t byte1,
                                                  int32_t byte2,
                                                  int32_t byte3,
                                                  int32_t byte4,
                                                  int32_t byte5);

void
libcrux_kyber_serialize_deserialize_then_decompress_5(Eurydice_slice serialized,
                                                      int32_t ret[256U]);

void
libcrux_kyber_serialize_compress_then_serialize_message(int32_t re[256U],
                                                        uint8_t ret[32U]);

#define LIBCRUX_KYBER_KYBER768_RANK_768 ((size_t)3U)

#define LIBCRUX_KYBER_KYBER768_RANKED_BYTES_PER_RING_ELEMENT_768               \
  (LIBCRUX_KYBER_KYBER768_RANK_768 *                                           \
   LIBCRUX_KYBER_CONSTANTS_BITS_PER_RING_ELEMENT / (size_t)8U)

#define LIBCRUX_KYBER_KYBER768_T_AS_NTT_ENCODED_SIZE_768                       \
  (LIBCRUX_KYBER_KYBER768_RANK_768 *                                           \
   LIBCRUX_KYBER_CONSTANTS_COEFFICIENTS_IN_RING_ELEMENT *                      \
   LIBCRUX_KYBER_CONSTANTS_BITS_PER_COEFFICIENT / (size_t)8U)

#define LIBCRUX_KYBER_KYBER768_VECTOR_U_COMPRESSION_FACTOR_768 ((size_t)10U)

#define LIBCRUX_KYBER_KYBER768_C1_BLOCK_SIZE_768                               \
  (LIBCRUX_KYBER_CONSTANTS_COEFFICIENTS_IN_RING_ELEMENT *                      \
   LIBCRUX_KYBER_KYBER768_VECTOR_U_COMPRESSION_FACTOR_768 / (size_t)8U)

#define LIBCRUX_KYBER_KYBER768_C1_SIZE_768                                     \
  (LIBCRUX_KYBER_KYBER768_C1_BLOCK_SIZE_768 * LIBCRUX_KYBER_KYBER768_RANK_768)

#define LIBCRUX_KYBER_KYBER768_VECTOR_V_COMPRESSION_FACTOR_768 ((size_t)4U)

#define LIBCRUX_KYBER_KYBER768_C2_SIZE_768                                     \
  (LIBCRUX_KYBER_CONSTANTS_COEFFICIENTS_IN_RING_ELEMENT *                      \
   LIBCRUX_KYBER_KYBER768_VECTOR_V_COMPRESSION_FACTOR_768 / (size_t)8U)

#define LIBCRUX_KYBER_KYBER768_CPA_PKE_SECRET_KEY_SIZE_768                     \
  (LIBCRUX_KYBER_KYBER768_RANK_768 *                                           \
   LIBCRUX_KYBER_CONSTANTS_COEFFICIENTS_IN_RING_ELEMENT *                      \
   LIBCRUX_KYBER_CONSTANTS_BITS_PER_COEFFICIENT / (size_t)8U)

#define LIBCRUX_KYBER_KYBER768_CPA_PKE_PUBLIC_KEY_SIZE_768                     \
  (LIBCRUX_KYBER_KYBER768_T_AS_NTT_ENCODED_SIZE_768 + (size_t)32U)

#define LIBCRUX_KYBER_KYBER768_CPA_PKE_CIPHERTEXT_SIZE_768                     \
  (LIBCRUX_KYBER_KYBER768_C1_SIZE_768 + LIBCRUX_KYBER_KYBER768_C2_SIZE_768)

#define LIBCRUX_KYBER_KYBER768_SECRET_KEY_SIZE_768                             \
  (LIBCRUX_KYBER_KYBER768_CPA_PKE_SECRET_KEY_SIZE_768 +                        \
   LIBCRUX_KYBER_KYBER768_CPA_PKE_PUBLIC_KEY_SIZE_768 +                        \
   LIBCRUX_KYBER_CONSTANTS_H_DIGEST_SIZE +                                     \
   LIBCRUX_KYBER_CONSTANTS_SHARED_SECRET_SIZE)

#define LIBCRUX_KYBER_KYBER768_ETA1 ((size_t)2U)

#define LIBCRUX_KYBER_KYBER768_ETA1_RANDOMNESS_SIZE                            \
  (LIBCRUX_KYBER_KYBER768_ETA1 * (size_t)64U)

#define LIBCRUX_KYBER_KYBER768_ETA2 ((size_t)2U)

#define LIBCRUX_KYBER_KYBER768_ETA2_RANDOMNESS_SIZE                            \
  (LIBCRUX_KYBER_KYBER768_ETA2 * (size_t)64U)

#define LIBCRUX_KYBER_KYBER768_IMPLICIT_REJECTION_HASH_INPUT_SIZE              \
  (LIBCRUX_KYBER_CONSTANTS_SHARED_SECRET_SIZE +                                \
   LIBCRUX_KYBER_KYBER768_CPA_PKE_CIPHERTEXT_SIZE_768)

void
libcrux_kyber_hash_functions_XOFx4___3size_t(uint8_t input[3U][34U],
                                             uint8_t ret[3U][840U]);

void
libcrux_kyber_matrix_sample_matrix_A___3size_t(uint8_t seed[34U],
                                               bool transpose,
                                               int32_t ret[3U][3U][256U]);

void
libcrux_kyber_ind_cpa_into_padded_array___34size_t(Eurydice_slice slice,
                                                   uint8_t ret[34U]);

void
libcrux_kyber_ind_cpa_into_padded_array___33size_t(Eurydice_slice slice,
                                                   uint8_t ret[33U]);

void
libcrux_kyber_hash_functions_PRF___128size_t(Eurydice_slice input,
                                             uint8_t ret[128U]);

void
libcrux_kyber_sampling_sample_from_binomial_distribution___2size_t(
  Eurydice_slice randomness,
  int32_t ret[256U]);

typedef struct
  K___libcrux_kyber_arithmetic_PolynomialRingElement_3size_t__uint8_t_s
{
  int32_t fst[3U][256U];
  uint8_t snd;
} K___libcrux_kyber_arithmetic_PolynomialRingElement_3size_t__uint8_t;

K___libcrux_kyber_arithmetic_PolynomialRingElement_3size_t__uint8_t
libcrux_kyber_ind_cpa_sample_vector_cbd_then_ntt___3size_t_2size_t_128size_t(
  uint8_t prf_input[33U],
  uint8_t domain_separator);

void
libcrux_kyber_arithmetic_add_to_ring_element___3size_t(int32_t lhs[256U],
                                                       int32_t (*rhs)[256U],
                                                       int32_t ret[256U]);

void libcrux_kyber_matrix_compute_As_plus_e___3size_t(
  int32_t (*matrix_A)[3U][256U],
  int32_t (*s_as_ntt)[256U],
  int32_t (*error_as_ntt)[256U],
  int32_t ret[3U][256U]);

void
libcrux_kyber_ind_cpa_serialize_secret_key___3size_t_1152size_t(
  int32_t key[3U][256U],
  uint8_t ret[1152U]);

void
libcrux_kyber_ind_cpa_serialize_public_key___3size_t_1152size_t_1184size_t(
  int32_t t_as_ntt[3U][256U],
  Eurydice_slice seed_for_a,
  uint8_t ret[1184U]);

typedef struct K___uint8_t_1152size_t__uint8_t_1184size_t__s
{
  uint8_t fst[1152U];
  uint8_t snd[1184U];
} K___uint8_t_1152size_t__uint8_t_1184size_t_;

typedef struct K___Eurydice_slice_uint8_t_Eurydice_slice_uint8_t_s
{
  Eurydice_slice fst;
  Eurydice_slice snd;
} K___Eurydice_slice_uint8_t_Eurydice_slice_uint8_t;

K___uint8_t_1152size_t__uint8_t_1184size_t_
libcrux_kyber_ind_cpa_generate_keypair___3size_t_1152size_t_1184size_t_1152size_t_2size_t_128size_t(
  Eurydice_slice key_generation_seed);

void
libcrux_kyber_serialize_kem_secret_key___2400size_t(
  Eurydice_slice private_key,
  Eurydice_slice public_key,
  Eurydice_slice implicit_rejection_value,
  uint8_t ret[2400U]);

typedef uint8_t libcrux_kyber_types_KyberPrivateKey___2400size_t[2400U];

void
libcrux_kyber_types__libcrux_kyber__types__KyberPrivateKey_SIZE__8__from___2400size_t(
  uint8_t value[2400U],
  uint8_t ret[2400U]);

typedef uint8_t libcrux_kyber_types_KyberPublicKey___1184size_t[1184U];

typedef struct libcrux_kyber_types_KyberKeyPair___2400size_t_1184size_t_s
{
  uint8_t sk[2400U];
  uint8_t pk[1184U];
} libcrux_kyber_types_KyberKeyPair___2400size_t_1184size_t;

libcrux_kyber_types_KyberKeyPair___2400size_t_1184size_t
libcrux_kyber_types__libcrux_kyber__types__KyberKeyPair_PRIVATE_KEY_SIZE__PUBLIC_KEY_SIZE___from___2400size_t_1184size_t(
  uint8_t sk[2400U],
  uint8_t pk[1184U]);

libcrux_kyber_types_KyberKeyPair___2400size_t_1184size_t
libcrux_kyber_generate_keypair___3size_t_1152size_t_2400size_t_1184size_t_1152size_t_2size_t_128size_t(
  uint8_t randomness[64U]);

libcrux_kyber_types_KyberKeyPair___2400size_t_1184size_t
libcrux_kyber_kyber768_generate_key_pair_768(uint8_t randomness[64U]);

void
libcrux_kyber_ind_cpa_into_padded_array___64size_t(Eurydice_slice slice,
                                                   uint8_t ret[64U]);

uint8_t*
  libcrux_kyber_types__libcrux_kyber__types__KyberPublicKey_SIZE__18__as_slice___1184size_t(
    uint8_t (*self)[1184U]);

void
libcrux_kyber_ind_cpa_deserialize_public_key___3size_t(
  Eurydice_slice public_key,
  int32_t ret[3U][256U]);

void
libcrux_kyber_ind_cpa_sample_ring_element_cbd___3size_t_128size_t_2size_t(
  uint8_t* prf_input,
  uint8_t* domain_separator,
  int32_t ret[3U][256U]);

void
libcrux_kyber_ntt_invert_ntt_montgomery___3size_t(int32_t re[256U],
                                                  int32_t ret[256U]);

void libcrux_kyber_matrix_compute_vector_u___3size_t(
  int32_t (*a_as_ntt)[3U][256U],
  int32_t (*r_as_ntt)[256U],
  int32_t (*error_1)[256U],
  int32_t ret[3U][256U]);

void libcrux_kyber_matrix_compute_ring_element_v___3size_t(
  int32_t (*t_as_ntt)[256U],
  int32_t (*r_as_ntt)[256U],
  int32_t (*error_2)[256U],
  int32_t (*message)[256U],
  int32_t ret[256U]);

void
libcrux_kyber_serialize_compress_then_serialize_10___320size_t(
  int32_t re[256U],
  uint8_t ret[320U]);

void
libcrux_kyber_serialize_compress_then_serialize_11___320size_t(
  int32_t re[256U],
  uint8_t ret[320U]);

void
libcrux_kyber_serialize_compress_then_serialize_ring_element_u___10size_t_320size_t(
  int32_t re[256U],
  uint8_t ret[320U]);

void
libcrux_kyber_ind_cpa_compress_then_serialize_u___3size_t_960size_t_10size_t_320size_t(
  int32_t input[3U][256U],
  uint8_t ret[960U]);

void
libcrux_kyber_serialize_compress_then_serialize_4___128size_t(
  int32_t re[256U],
  uint8_t ret[128U]);

void
libcrux_kyber_serialize_compress_then_serialize_5___128size_t(
  int32_t re[256U],
  uint8_t ret[128U]);

void
libcrux_kyber_serialize_compress_then_serialize_ring_element_v___4size_t_128size_t(
  int32_t re[256U],
  uint8_t ret[128U]);

void
libcrux_kyber_ind_cpa_into_padded_array___1088size_t(Eurydice_slice slice,
                                                     uint8_t ret[1088U]);

void
libcrux_kyber_ind_cpa_encrypt___3size_t_1088size_t_1152size_t_960size_t_128size_t_10size_t_4size_t_320size_t_2size_t_128size_t_2size_t_128size_t(
  Eurydice_slice public_key,
  uint8_t message[32U],
  Eurydice_slice randomness,
  uint8_t ret[1088U]);

typedef uint8_t libcrux_kyber_types_KyberCiphertext___1088size_t[1088U];

typedef struct
  K___libcrux_kyber_types_KyberCiphertext__1088size_t___uint8_t_32size_t__s
{
  uint8_t fst[1088U];
  uint8_t snd[32U];
} K___libcrux_kyber_types_KyberCiphertext__1088size_t___uint8_t_32size_t_;

K___libcrux_kyber_types_KyberCiphertext__1088size_t___uint8_t_32size_t_
  libcrux_kyber_encapsulate___3size_t_1088size_t_1184size_t_1152size_t_960size_t_128size_t_10size_t_4size_t_320size_t_2size_t_128size_t_2size_t_128size_t(
    uint8_t (*public_key)[1184U],
    uint8_t randomness[32U]);

K___libcrux_kyber_types_KyberCiphertext__1088size_t___uint8_t_32size_t_
  libcrux_kyber_kyber768_encapsulate_768(uint8_t (*public_key)[1184U],
                                         uint8_t randomness[32U]);

K___Eurydice_slice_uint8_t_Eurydice_slice_uint8_t
  libcrux_kyber_types__libcrux_kyber__types__KyberPrivateKey_SIZE__12__split_at___2400size_t(
    uint8_t (*self)[2400U],
    size_t mid);

void
libcrux_kyber_serialize_deserialize_then_decompress_ring_element_u___10size_t(
  Eurydice_slice serialized,
  int32_t ret[256U]);

void
libcrux_kyber_ntt_ntt_vector_u___10size_t(int32_t re[256U], int32_t ret[256U]);

void
libcrux_kyber_ind_cpa_deserialize_then_decompress_u___3size_t_1088size_t_10size_t(
  uint8_t* ciphertext,
  int32_t ret[3U][256U]);

void
libcrux_kyber_serialize_deserialize_then_decompress_ring_element_v___4size_t(
  Eurydice_slice serialized,
  int32_t ret[256U]);

void
libcrux_kyber_ind_cpa_deserialize_secret_key___3size_t(
  Eurydice_slice secret_key,
  int32_t ret[3U][256U]);

void libcrux_kyber_matrix_compute_message___3size_t(
  int32_t (*v)[256U],
  int32_t (*secret_as_ntt)[256U],
  int32_t (*u_as_ntt)[256U],
  int32_t ret[256U]);

void
libcrux_kyber_ind_cpa_decrypt___3size_t_1088size_t_960size_t_10size_t_4size_t(
  Eurydice_slice secret_key,
  uint8_t* ciphertext,
  uint8_t ret[32U]);

void
libcrux_kyber_ind_cpa_into_padded_array___1120size_t(Eurydice_slice slice,
                                                     uint8_t ret[1120U]);

Eurydice_slice
  libcrux_kyber_types__libcrux_kyber__types__KyberCiphertext_SIZE__1__as_ref___1088size_t(
    uint8_t (*self)[1088U]);

void
libcrux_kyber_hash_functions_PRF___32size_t(Eurydice_slice input,
                                            uint8_t ret[32U]);

uint8_t
libcrux_kyber_constant_time_ops_compare_ciphertexts_in_constant_time___1088size_t(
  Eurydice_slice lhs,
  Eurydice_slice rhs);

void
  libcrux_kyber_decapsulate___3size_t_2400size_t_1152size_t_1184size_t_1088size_t_1152size_t_960size_t_128size_t_10size_t_4size_t_320size_t_2size_t_128size_t_2size_t_128size_t_1120size_t(
    uint8_t (*secret_key)[2400U],
    uint8_t (*ciphertext)[1088U],
    uint8_t ret[32U]);

void libcrux_kyber_kyber768_decapsulate_768(uint8_t (*secret_key)[2400U],
                                            uint8_t (*ciphertext)[1088U],
                                            uint8_t ret[32U]);

#define LIBCRUX_KYBER_KEY_GENERATION_SEED_SIZE                                 \
  (LIBCRUX_KYBER_CONSTANTS_CPA_PKE_KEY_GENERATION_SEED_SIZE +                  \
   LIBCRUX_KYBER_CONSTANTS_SHARED_SECRET_SIZE)

#define __libcrux_kyber_H_DEFINED
#endif
