/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/bhargava/Desktop/repositories/eurydice/eurydice --config ../../kyber-c.yaml ../libcrux_kyber.llbc
  F* version: a32b316e
  KaRaMeL version: 08bfa78a
 */

#ifndef __libcrux_digest_H
#define __libcrux_digest_H

#include "eurydice_glue.h"

extern void libcrux_digest_sha3_512(Eurydice_slice x0, uint8_t x1[64U]);

extern void libcrux_digest_sha3_256(Eurydice_slice x0, uint8_t x1[32U]);

#define libcrux_digest_shake256(x_0, x_1, x_2, _ret_t) libcrux_digest_shake256_(x_0, x_1, x_2)

extern void libcrux_digest_shake256_(size_t x0, Eurydice_slice x1, uint8_t *x2);

extern libcrux_digest_Shake128StateX2 libcrux_digest_shake128_init_x2(void);

extern libcrux_digest_Shake128StateX3 libcrux_digest_shake128_init_x3(void);

extern libcrux_digest_Shake128StateX4 libcrux_digest_shake128_init_x4(void);

extern void
libcrux_digest_shake128_absorb_final_x2(
  libcrux_digest_Shake128StateX2 *x0,
  Eurydice_slice x1,
  Eurydice_slice x2
);

extern void
libcrux_digest_shake128_absorb_final_x3(
  libcrux_digest_Shake128StateX3 *x0,
  Eurydice_slice x1,
  Eurydice_slice x2,
  Eurydice_slice x3
);

extern void
libcrux_digest_shake128_absorb_final_x4(
  libcrux_digest_Shake128StateX4 *x0,
  Eurydice_slice x1,
  Eurydice_slice x2,
  Eurydice_slice x3,
  Eurydice_slice x4
);

extern void
libcrux_digest_shake128_squeeze_nblocks_x2(
  libcrux_digest_Shake128StateX2 *x0,
  uint8_t* output,
  size_t output_bytes
);

extern void
libcrux_digest_shake128_squeeze_nblocks_x3(
  libcrux_digest_Shake128StateX2 *x0,
  uint8_t* output,
  size_t output_bytes
);

extern void
libcrux_digest_shake128_squeeze_nblocks_x4(
  libcrux_digest_Shake128StateX2 *x0,
  uint8_t* output,
  size_t output_bytes
);


#define __libcrux_digest_H_DEFINED
#endif
