/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/franziskus/repos/eurydice//eurydice --config ../../kyber-c.yaml ../libcrux_kyber.llbc
  F* version: a32b316e
  KaRaMeL version: a1e1b1f2
 */

#ifndef __libcrux_digest_H
#define __libcrux_digest_H

#include "eurydice_glue.h"
#include "libcrux_hacl_glue.h"

extern void libcrux_digest_sha3_512(Eurydice_slice x0, uint8_t x1[64U]);

extern void libcrux_digest_sha3_256(Eurydice_slice x0, uint8_t x1[32U]);

#define libcrux_digest_shake256(x_0, x_1, x_2, _ret_t) libcrux_digest_shake256_(x_0, x_1, x_2)

extern void libcrux_digest_shake256_(size_t x0, Eurydice_slice x1, uint8_t *x2);

extern libcrux_digest_Shake128State libcrux_digest_shake128_init(void);

extern void
libcrux_digest_shake128_absorb_final(libcrux_digest_Shake128State *x0, Eurydice_slice x1);

#define libcrux_digest_shake128_squeeze_nblocks(x_0, x_1, x_2, _ret_t) libcrux_digest_shake128_squeeze_nblocks_(x_0, x_1, x_2)

extern void
libcrux_digest_shake128_squeeze_nblocks_(
  size_t x0,
  libcrux_digest_Shake128State *x1,
  uint8_t *x2
);


#define __libcrux_digest_H_DEFINED
#endif
