/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/franziskus/.hax/eurydice/eurydice --config ../../kyber-c.yaml ../libcrux_kyber.llbc
  F* version: a32b316e
  KaRaMeL version: 08bfa78a
 */

#ifndef __libcrux_platform_H
#define __libcrux_platform_H

#include "eurydice_glue.h"

extern bool libcrux_platform_simd256_support(void);


#define __libcrux_platform_H_DEFINED
#endif
