/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: eurydice ../libcrux_kyber.llbc --config config.yaml
  F* version: 58c915a8
  KaRaMeL version: 56c5c145
 */

#ifndef __libcrux_platform_H
#define __libcrux_platform_H

#include "eurydice_glue.h"

extern bool libcrux_platform_simd256_support(void);


#define __libcrux_platform_H_DEFINED
#endif
