/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../../../eurydice/eurydice --config ../../kyber-c.yaml ../libcrux_kyber.llbc
  F* version: b5cb71b8
  KaRaMeL version: 1282f04f
 */

#ifndef __libcrux_digest_H
#define __libcrux_digest_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "eurydice_glue.h"
#include "libcrux_hacl_glue.h"

void libcrux_sha3_portable_sha512(Eurydice_slice x0, Eurydice_slice x1);

void libcrux_sha3_portable_sha256(Eurydice_slice x0, Eurydice_slice x1);

#define libcrux_digest_shake256(x_0, x_1, x_2, _ret_t) libcrux_digest_shake256_(x_0, x_1, x_2)

void libcrux_sha3_portable_shake256_(size_t x0, uint8_t *x2, Eurydice_slice x1);

#if defined(__cplusplus)
}
#endif

#define __libcrux_digest_H_DEFINED
#endif
